# Generated by Django 5.0.1 on 2024-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
    ]
